---
Rooms:
  - Name: Bed Room
    Accesories:
      - Name: Fan
        Type: Pin
        Value: 18
      - Name: Front Light
        Type: Pin
        Value: 17
      - Name: Back Light
        Type: Pin
        Value: 27
      - Name: Bright Light
        Type: Pin
        Value: 22
  - Name: Bath Room
    Accesories:
      - Name: Light
        Type: Pin
        Value: 23
  - Name: Servers
    Accesories:
      - Name: Champ
        Type: Script
        Value: ./echo.sh

Settings:
  SSL: 
    Enabled: False
    Path: default
    Certificate: WebGPIO.cer
    Key: WebGPIO.key