---
Rooms:
  - Name: Back Room
    Appliances:
      - Name: AirTemp
        Location: Air Temp
        Type: Temp
        Address: 000002cd96b7
      - Name: Front Light
        Type: GPIO
        Pin: 26
      - Name: Back Light
        Type: GPIO
        Pin: 20
        Duration: 2
  - Name: Den
    Appliances:
      - Name: ResisterTemp
        Location: Resister Temp
        Type: Temp
        Address: 0000033723fc
      - Name: Table Light
        Type: GPIO
        Pin: 12
        Inverted: 1
  - Name: Scripts
    Appliances:
      - Name: Internet
        Type: Script
        Status: ping -c 1 8.8.8.8 > /dev/null
        Timeout: 0.3
      - Name: Apache
        Type: Script
        Status: sudo systemctl is-active --quiet apache2 2> /dev/null
        Action: 
          On: sudo systemctl start apache2
          Off: sudo systemctl stop apache2
      - Name: proFTPd
        Type: Script
        Status: sudo systemctl is-active --quiet proftpd 2> /dev/null
        Action: 
          On: sudo systemctl start proftpd
          Off: sudo systemctl stop proftpd


Settings:
#  GPIOMode: BOARD
#  Host: 0.0.0.0
#  Port: 8080
#  Debug: True
#  SSL:
#    Enabled: False
#    Path: default
#    Certificate: WebGPIO.cer
#    Key: WebGPIO.key
#  Inverted: False
#  RefreshRate: 3